from selgui import *
from lib2to3.pgen2 import driver
import time
import pyautogui
import pydirectinput

def play_mission_snipe_100():
    for i in range(100):
        try:
            selgui.find(r'InCampaign/Halo_Reach/Nightfall/restart.png',.9)
            print("found restart button, going to restart current mission, assuming this is within the current challenge loop...")
            selgui.click(r'InCampaign/Halo_Reach/Nightfall/restart.png',.9)
            time.sleep(.25)
            selgui.click(r'InCampaign/Halo_Reach/Nightfall/yes.png',.9)
            time.sleep(2)
        except:
            print("no restart button found, continuing with mission...")
        print("starting Nightfall automation mission now.")
        time.sleep(2)
        pydirectinput.keyDown('space')
        time.sleep(.25)
        pydirectinput.keyUp('space')
        print("skipped campaign cutscene")
        while True:
            try:
                selgui.find(r'InCampaign/Halo_Reach/Nightfall/start_confirm.png',.7)
                print("confirmed mission has started.")
                break
            except:
                pass
        print("beginning to move in script...")
        pydirectinput.keyDown('w')
        time.sleep(.5)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(.5)
        pydirectinput.keyUp('d')
        pydirectinput.keyDown('w')
        time.sleep(3.4)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(1)
        pydirectinput.keyUp('d')
        pydirectinput.keyDown('w')
        time.sleep(1.75)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('a')
        time.sleep(.5)
        pydirectinput.keyUp('a')
        pydirectinput.keyDown('w')
        time.sleep(.25)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('a')
        pydirectinput.keyDown('w')
        time.sleep(4.5)
        pydirectinput.keyUp('a')
        pydirectinput.keyUp('w')
        time.sleep(.25)
        pydirectinput.keyDown('w')
        time.sleep(.5)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(1.625)
        pydirectinput.keyUp('d')
        time.sleep(.25)
        pydirectinput.keyDown('w')
        time.sleep(1.45)
        pydirectinput.keyUp('w')
        #print("moving mouse")
        #pydirectinput.mouseUp(None,15)
        #pydirectinput.moveTo(mousex,mousey-5)
        #time.sleep(.25)
        #pydirectinput.click()
        #pydirectinput.press('space')
        #pydirectinput.click()
        time.sleep(.25)
        print("shooting sniper at elite")
        pydirectinput.mouseDown(button='left')
        pydirectinput.mouseUp(button='left')
        time.sleep(1)
        pydirectinput.mouseDown(button='left')
        pydirectinput.mouseUp(button='left')
        time.sleep(1)
        pydirectinput.mouseDown(button='left')
        pydirectinput.mouseUp(button='left')
        time.sleep(1)
        pydirectinput.press('esc')

def play_mission_snipe_75():
    for i in range(75):
        try:
            selgui.find(r'InCampaign/Halo_Reach/Nightfall/restart.png',.9)
            print("found restart button, going to restart current mission, assuming this is within the current challenge loop...")
            selgui.click(r'InCampaign/Halo_Reach/Nightfall/restart.png',.9)
            time.sleep(.25)
            selgui.click(r'InCampaign/Halo_Reach/Nightfall/yes.png',.9)
            time.sleep(2)
        except:
            print("no restart button found, continuing with mission...")
        print("starting Nightfall automation mission now.")
        time.sleep(2)
        pydirectinput.keyDown('space')
        time.sleep(.25)
        pydirectinput.keyUp('space')
        print("skipped campaign cutscene")
        while True:
            try:
                selgui.find(r'InCampaign/Halo_Reach/Nightfall/start_confirm.png',.7)
                print("confirmed mission has started.")
                break
            except:
                pass
        print("beginning to move in script...")
        pydirectinput.keyDown('w')
        time.sleep(.5)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(.5)
        pydirectinput.keyUp('d')
        pydirectinput.keyDown('w')
        time.sleep(3.4)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(1)
        pydirectinput.keyUp('d')
        pydirectinput.keyDown('w')
        time.sleep(1.75)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('a')
        time.sleep(.5)
        pydirectinput.keyUp('a')
        pydirectinput.keyDown('w')
        time.sleep(.25)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('a')
        pydirectinput.keyDown('w')
        time.sleep(4.5)
        pydirectinput.keyUp('a')
        pydirectinput.keyUp('w')
        time.sleep(.25)
        pydirectinput.keyDown('w')
        time.sleep(.5)
        pydirectinput.keyUp('w')
        pydirectinput.keyDown('d')
        time.sleep(1.625)
        pydirectinput.keyUp('d')
        time.sleep(.25)
        pydirectinput.keyDown('w')
        time.sleep(1.45)
        pydirectinput.keyUp('w')
        #print("moving mouse")
        #pydirectinput.mouseUp(None,15)
        #pydirectinput.moveTo(mousex,mousey-5)
        #time.sleep(.25)
        #pydirectinput.click()
        #pydirectinput.press('space')
        #pydirectinput.click()
        time.sleep(.25)
        print("shooting sniper at elite")
        pydirectinput.mouseDown(button='left')
        pydirectinput.mouseUp(button='left')
        time.sleep(1)
        pydirectinput.mouseDown(button='left')
        pydirectinput.mouseUp(button='left')
        time.sleep(1)
        pydirectinput.press('esc')




